# Site settings
title: TTU CSC Documentation
email: 
description: > # this means to ignore newlines until "baseurl:"
  This page hosts the documentation for TTU's CSC 2101 class, with
  potential for other classes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ttu-csc.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
